### ISSUE TITLE
unable to get audio's link

### ISSUE THREAD

**Issue by avenir2027** [mos9527/pyncmd#4]
I deployed one, but it can't get the audio link

**Comment by avenir2027** [comment]
I deployed it before, and I can get the audio link.

**Comment by mos9527** [comment]
vercel部分region的IP会被网易云识别成海外
此时如果没有配置登录态就有可能拿不到音频文件的url
可以尝试一下几点：

> 更改你实例的 Region

**Comment by avenir2027** [comment]
I don't know how to change
