### ISSUE TITLE
I don't know how to do

### ISSUE THREAD

**Issue by avenir2027** [mos9527/pyncmd#5]
I tried to change the 'real IP=''' and 'Serverless Function Region'

**Comment by avenir2027** [comment]
![IMG_20220831_113639](https://user-images.githubusercontent.com/98002613/187587673-fbe40528-27d5-4311-9d4f-c79e072f34aa.jpg)

**Comment by avenir2027** [comment]
![IMG_20220831_114328](https://user-images.githubusercontent.com/98002613/187587967-f142bb96-a004-495a-91d9-cb26b402454a.jpg)

**Comment by avenir2027** [comment]
https://./api/pyncm?withIP=client&module=track&method=GetTrackAudio&song_ids=431259256&bitrate=320000
>{"data": [{"id": 431259256, "url": null, "br": 0, "size": 0, "md5": null, "code": -110, "expi": 1200, "type": null, "gain": 0.0, "fee": 1, "uf": null, "payed": 0, "flag": 4, "canExtend": false, "freeTrialInfo": null, "level": null, "encodeType": null, "freeTrialPrivilege": {"resConsumable": true, "userConsumable": false, "listenType": null}, "freeTimeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "type": 0, "remainTime": 0}, "urlSource": 0, "rightSource": 0, "podcastCtrp": null, "effectTypes": null, "time": 0}], "code": 200, "requestIP": "clent", "clientIP": "*"}

**Comment by mos9527** [comment]
试试把 withIP=client 换成 withIP=118.118.118.118

这里是我的配置了登录态的实例，在不改ip的前提下也是能获得url的
`https://pyncmd.vercel.app/api/pyncm?withIP=client&module=track&method=GetTrackAudio&song_ids=431259256&bitrate=320000`

**Comment by avenir2027** [comment]
> 试试把 withIP=client 换成 withIP=118.118.118.118
> 
> 这里是我的配置了登录态的实例，在不改ip的前提下也是能获得url的 `https://pyncmd.vercel.app/api/pyncm?withIP=client&module=track&method=GetTrackAudio&song_ids=431259256&bitrate=320000`

{"data": [{"id": 431259256, "url": null, "br": 0, "size": 0, "md5": null, "code": -110, "expi": 1200, "type": null, "gain": 0.0, "fee": 1, "uf": null, "payed": 0, "flag": 4, "canExtend": false, "freeTrialInfo": null, "level": null, "encodeType": null, "freeTrialPrivilege": {"resConsumable": true, "userConsumable": false, "listenType": null}, "freeTimeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "type": 0, "remainTime": 0}, "urlSource": 0, "rightSource": 0, "podcastCtrp": null, "effectTypes": null, "time": 0}], "code": 200, "requestIP": "118.118.118.118", "clientIP": "164.70.122.158"}

**Comment by avenir2027** [comment]
It seems that the newly deployed project is not working properly?

**Comment by avenir2027** [comment]
I get the login information through pyncm(pip install pyncm,pyncm --phone --password --save) and add it to vercel, but it still can't get the audio link

**Comment by mos9527** [comment]
检查了下，发现没有**正确**配置登录态的实例仅能拿到部分歌曲的url (e.g 1920696213)
这里应该是pyncmd没有正确获取游客token的问题
登录正常时，响应报文里应有`server:你的昵称`键值，其次vercel的live log也会有相关信息
能发下请求时vercel的日志吗？

**Comment by avenir2027** [comment]
> 检查了下，发现没有**正确**配置登录态的实例仅能拿到部分歌曲的url (e.g 1920696213) 这里应该是pyncmd没有正确获取游客token的问题 登录正常时，响应报文里应有`server:你的昵称`键值，其次vercel的live log也会有相关信息 能发下请求时vercel的日志吗？

thank you,how to get?I send it out.

**Comment by avenir2027** [comment]
I tried this ID(1920696213), and item can get the audio link.

**Comment by avenir2027** [comment]
added login.info:
{"data": [{"id": 536623501, "url": null, "br": 0, "size": 0, "md5": null, "code": -110, "expi": 1200, "type": null, "gain": 0.0, "fee": 1, "uf": null, "payed": 0, "flag": 4, "canExtend": false, "freeTrialInfo": null, "level": null, "encodeType": null, "freeTrialPrivilege": {"resConsumable": true, "userConsumable": false, "listenType": null}, "freeTimeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "type": 0, "remainTime": 0}, "urlSource": 0, "rightSource": 0, "podcastCtrp": null, "effectTypes": null, "time": 0}], "code": 200, "requestIP": "118.118.118.118", "clientIP": ""}

**Comment by avenir2027** [comment]
![IMG_20220901_125552](https://user-images.githubusercontent.com/98002613/187834499-10fc6f11-5aa9-4505-9ae6-f69d06989055.jpg)

**Comment by avenir2027** [comment]
> 检查了下，发现没有**正确**配置登录态的实例仅能拿到部分歌曲的url (e.g 1920696213) 这里应该是pyncmd没有正确获取游客token的问题 登录正常时，响应报文里应有`server:你的昵称`键值，其次vercel的live log也会有相关信息 能发下请求时vercel的日志吗？

![IMG_20220901_125552](https://user-images.githubusercontent.com/98002613/187834546-c53e760a-f92e-4739-8edb-da9eab83eed3.jpg)

**Comment by mos9527** [comment]
应该是登录态配置问题，毕竟环境变量没加
看看 [README?](https://github.com/mos9527/pyncmd#api-%E6%9C%8D%E5%8A%A1%E8%AE%BE%E7%BD%AE)

**Comment by avenir2027** [comment]
It was possible not to add login information before,is it still possible now?

**Comment by avenir2027** [comment]
> 应该是登录态配置问题，毕竟环境变量没加 看看 [README?](https://github.com/mos9527/pyncmd#api-%E6%9C%8D%E5%8A%A1%E8%AE%BE%E7%BD%AE)

It was possible not to add login information before,is it still possible now?

**Comment by avenir2027** [comment]
{"code": 503, "message": "{'loginType': 1, 'code': 250, 'message': '当前登录存在安全风险，请稍后再试'}"}

**Comment by avenir2027** [comment]
{"code": 503, "message": "{'msg': '帐号或密码错误', 'code': 502, 'message': '帐号或密码错误'}"}
the password is correct. I used the same password to log in successfully on the app.

**Comment by avenir2027** [comment]
I got the login info through pyncm and added the environment variable,and now the project can get the audio link,but I also want to ask a question,can it not add the login info as before?

**Comment by avenir2027** [comment]
> 应该是登录态配置问题，毕竟环境变量没加 看看 [README?](https://github.com/mos9527/pyncmd#api-%E6%9C%8D%E5%8A%A1%E8%AE%BE%E7%BD%AE)

I got the login info through pyncm and added the environment variable,and now the project can get the audio link,but I also want to ask a question,can it not add the login info as before?

**Comment by avenir2027** [comment]
> 指的是[腾讯云 serverless branch](https://github.com/mos9527/pyncmd/tree/serverless) 吗？ 之前是因为腾讯云的scf没有environ的配置功能（至少我没找到），所以用了添加session文件管理登录态的方案 vercel提供了实例environ的配置选项，于是就没把旧方案保留下来 毕竟redeploy不需要加一步添加session的过程

I've deployed this item on vercel before, and it works normal without adding login info, but now it can't get the audio link without adding login info,can it works normal without adding login info as before?

**Comment by avenir2027** [comment]
has netease added restrictions on the server side? can you bypass the restrictions without adding login info?

**Comment by avenir2027** [comment]
the project I deployed on vercel already works normal after adding the login info,but can it works normal without adding login info as before?

**Comment by avenir2027** [comment]
the project I deployed on vercel already works normal after adding the login info,but can it works normal without adding login info as before?

**Comment by mos9527** [comment]
刚刚向`pyncm`加了匿名登录相关的API，经测试应该能在无手动配置登录态时正确取得URL了
可以看看[目前没有配置登录态的实例](https://pyncmd.vercel.app/?trackId=459717339)。注意下播放列表菜单里的“服务提供"

**Comment by avenir2027** [comment]
> 刚刚向`pyncm`加了匿名登录相关的API，经测试应该能在无手动配置登录态时正确取得URL了 可以看看[目前没有配置登录态的实例](https://pyncmd.vercel.app/?trackId=459717339)。注意下播放列表菜单里的“服务提供"

not all ids can get the link, ex.536623501

**Comment by mos9527** [comment]
这些都是VIP单曲,没有配置相关帐号自然无法取得URL
准确地说是fee的值,这点[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)做过文档:
```fee:,
  0: 免费或无版权
  1: VIP 歌曲
  4: 购买专辑
  8: 非会员可免费播放低音质，会员可播放高音质及下载
  fee 为 1 或 8 的歌曲均可单独购买 2 元单曲
```
比如下面在没有配置登录态时的几个例子
```javascript
{"data": [{"id": 431259256, "url": null, ..., "fee": 1, "uf": null, "payed": 0, "flag": 4, "canExtend": false, "freeTrialInfo": null, "level": null, "encodeType": null, "freeTrialPrivilege": {"resConsumable": true, "userConsumable": false, "listenType": null}, "freeTimeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "type": 0, "remainTime": 0}, "urlSource": 0, "rightSourc...
```
```javascript
{"data": [{"id": 33937479, "url": ..., "fee": 0, "uf": null, "payed": 0, "flag": 256, "canExtend": false, "freeTrialInfo": null, "level": "exhigh", "encodeType": "mp3", "freeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "listenType": null}, "freeTimeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "type": 0, "remainTime": 0}, "urlSource": 0, "rightSource": 0, ...
```
正确配置(会员帐号)后
```javascript
{"data": [{"id": 431259256, "url": "http://m701.music.126.net/20220903195028/a57224dd763b51cf821f61af65e5cd22/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/14941860290/2010/d733/e00a/10d3ef9dfe6eebd5d119e2d6ce3c1e06.mp3", "br": 320000, "size": 8296533, "md5": "10d3ef9dfe6eebd5d119e2d6ce3c1e06", "code": 200, "expi": 1200, "type": "mp3", "gain": 0.0, "fee": 1, "uf": null, "payed": 1, "flag": 4, "canExtend": false, "freeTrialInfo": null, "level": "exhigh", "encodeType": "mp3", "freeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "listenType": null}, "freeTimeTrialPrivilege": {"resConsumable": false, "u
```
```javascript
{"data": [{"id": 33937479, "url": "http://m7.music.126.net/20220903195152/ac5f183b294f5f405f87aca5a436d31a/ymusic/c9ae/d612/a398/8e125cf0ac05ebeef68ce5752331cf10.flac", "br": 1232899, "size": 48013205, "md5": "8e125cf0ac05...
````

**Comment by avenir2027** [comment]
> 这些都是VIP单曲,没有配置相关帐号自然无法取得URL 准确地说是fee的值,这点[NeteaseCloudMusicApi](https://github.com/Binaryify/NeteaseCloudMusicApi)做过文档:
> 
> ```
>   0: 免费或无版权
>   1: VIP 歌曲
>   4: 购买专辑
>   8: 非会员可免费播放低音质，会员可播放高音质及下载
>   fee 为 1 或 8 的歌曲均可单独购买 2 元单曲
> ```
> 
> 比如下面在没有配置登录态时的几个例子
> 
> ```js
> {"data": [{"id": 431259256, "url": null, ..., "fee": 1, "uf": null, "payed": 0, "flag": 4, "canExtend": false, "freeTrialInfo": null, "level": null, "encodeType": null, "freeTrialPrivilege": {"resConsumable": true, "userConsumable": false, "listenType": null}, "freeTimeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "type": 0, "remainTime": 0}, "urlSource": 0, "rightSourc...
> ```
> 
> ```js
> {"data": [{"id": 33937479, "url": ..., "fee": 0, "uf": null, "payed": 0, "flag": 256, "canExtend": false, "freeTrialInfo": null, "level": "exhigh", "encodeType": "mp3", "freeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "listenType": null}, "freeTimeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "type": 0, "remainTime": 0}, "urlSource": 0, "rightSource": 0, ...
> ```
> 
> 正确配置(会员帐号)后
> 
> ```js
> {"data": [{"id": 431259256, "url": "http://m701.music.126.net/20220903195028/a57224dd763b51cf821f61af65e5cd22/jdymusic/obj/wo3DlMOGwrbDjj7DisKw/14941860290/2010/d733/e00a/10d3ef9dfe6eebd5d119e2d6ce3c1e06.mp3", "br": 320000, "size": 8296533, "md5": "10d3ef9dfe6eebd5d119e2d6ce3c1e06", "code": 200, "expi": 1200, "type": "mp3", "gain": 0.0, "fee": 1, "uf": null, "payed": 1, "flag": 4, "canExtend": false, "freeTrialInfo": null, "level": "exhigh", "encodeType": "mp3", "freeTrialPrivilege": {"resConsumable": false, "userConsumable": false, "listenType": null}, "freeTimeTrialPrivilege": {"resConsumable": false, "u
> ```
> 
> ```js
> {"data": [{"id": 33937479, "url": "http://m7.music.126.net/20220903195152/ac5f183b294f5f405f87aca5a436d31a/ymusic/c9ae/d612/a398/8e125cf0ac05ebeef68ce5752331cf10.flac", "br": 1232899, "size": 48013205, "md5": "8e125cf0ac05...
> ```

previously, I used unblockneteasemusic to replace the source of the audio with it,and I could get the audio link of the vip songs,ex.459925512,but now the login info must be configured.

**Comment by mos9527** [comment]
[UNM](https://github.com/UnblockNeteaseMusic/server) 用了我的实例（配置了VIP帐号），所以能直接解锁网易云的这些歌曲
自己搭建服务而不添加会员帐号是自然不能越权拿到这些歌曲的url的，一直如此

**Comment by avenir2027** [comment]
> [UNM](https://github.com/UnblockNeteaseMusic/server) 用了我的实例（配置了VIP帐号），所以能直接解锁网易云的这些歌曲 自己搭建服务而不添加会员帐号是自然不能越权拿到这些歌曲的url的，一直如此

O,I only replaced the link under provider before(I recently discovered that there are links to sources in app.js/bridge.js.),actually,it got the link from your project,your project is configured with login, so I can go to the link of vip songs before.

**Comment by avenir2027** [comment]
thank you.

**Comment by avenir2027** [comment]
using your project to get login info returned that environment variable is not empty,but the service provider is shown as anonymous.

**Comment by avenir2027** [comment]
using your project to get login info returned that environment variable is not empty,but the service provider is shown as anonymous.

**Comment by avenir2027** [comment]
using your project to get login info returned that environment variable is not empty,but the service provider is shown as anonymous.
