### ISSUE TITLE
Question about login

### ISSUE THREAD

**Issue by mario6714** [mos9527/pyncmd#6]
How i can use another countrycode?

like this?

[Vercel 提供的域名]/api/pyncm?module=identity&phone=[MyNumber]&pwd=[MyPassword]&countrycode=[another countrycode (not 86)]

It gives me the following error:

code | 503
-- | --
message | "{'code': 400}"

Thanks

**Comment by mos9527** [comment]
[加入`&ctcode=...`即可](https://github.com/mos9527/pyncmd#%E9%85%8D%E7%BD%AE%E7%BD%91%E6%98%93%E4%BA%91%E8%B4%A6%E5%8F%B7)

**Comment by mos9527** [comment]
不加`[`,`]`
形如`.../api/pyncm?module=identity&phone=1111111111&pwd=111111&ctcode=51`
邮箱登录还没实现，毕竟注册都需要手机号(?)
暂时不考虑加入

**Comment by mos9527** [comment]
Huh.
Seems like accounts registered outside Mainland China will be rather troublesome to login with plaintext phone & password
With any luck, adding `&withIP=client` to your URL might solve your issue...hopefully
i.e. `.../api/pyncm?module=identity&phone=1111111111&pwd=111111&ctcode=51&withIP=client`

`pyncmd` essentially is a reverse proxy to Netease servers, and this will report your own IP (that is, the one you used to access Vercel) as the originating IP that actually makes the request to Netease, which may resolve code 10004?

**Comment by mos9527** [comment]
W/O the quotation marks. i.e. `PYNCM...`

**Comment by mos9527** [comment]
It *sort of* is. There's a lot of rate-limiting form NetEase recently that actually affected my personal usage of my account.
Apparently **A LOT** of people uses this site (~100k hits daily!) so I guess that's inevitable.
Things have smoothed out a bit with some recent changes I made but still, `pyncmd` cannot guarantee 100% availbility.

Anyways, as long as no DMCAs or legal requests hit this project, it will be and continue to be free for use.
Though thus far NetEase doesn't really seems to care about content management all that much? Guess we'll see.

Glad to help👌

**Comment by mos9527** [comment]
Nope. Since A. `pyncm` (not `pyncmd`) can handle phone/email/QR logins already & B. Many cookie keys are absent from Web cookies so it *won't* even work with most of NE's apis.

That said,you **CAN** login locally without sending your plaintext password to Vercel. Check out [pyncm](https://github.com/mos9527/pyncm). The `--save` function stores the session info (which is the exact same thing `pyncmd` uses) in base64 into a file so you can just use that instead.
